language: php
php:
  - 7.0
  - 7.1

install:
    # flags to pass to install
    - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
    # install dependencies using system provided composer binary
    - composer install $flags

script:
  - vendor/bin/phpspec run --config=phpspec.yml --no-interaction

notifications:
  email:
    - daniel.steiner@gmx.de